version: '3'
services:
#mssql docker
  evet-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - evetnet

  evet-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:eVet=Server=evet-sql,1433;Database=150131;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 6670:80
    networks:
      - evetnet      
    links:
      - evet-sql
    depends_on:
      - evet-sql

networks:
  evetnet:
    driver: bridge 